### PR TITLE
feat: render message log

### PR DESCRIPTION
**Pull request by dodumosu**
adds the ability to view the message log for logged-in users

### CODE REVIEW

**Comment by dodumosu** [comment]
@takinbo a gentle reminder on this

**Comment by takinbo** [comment]
@dodumosu can you fix the conflict and ensure that it works so I can review and merge?

**Comment by dodumosu** [comment]
@takinbo fixed. no apparent issues when testing

**Review by takinbo — APPROVED** [review]
LGTM

**Pull request merged**
